### ISSUE TITLE
Mapbox Tiling Problems (Possibly Since Changes to MercatorTiledImageLayer)

### ISSUE THREAD

**Issue by robmilton** [WorldWindEarth/WorldWindJava#53]
### Description
We had created a copy of MercatorTiledImageLayer from WWJ v2.1.0 with the only change being that we made the "splitScale" variable public.  This allowed us to influence the "needToSplit" resulting in better looking maps from Mapbox.

We have several Mapbox layers containing raster data and several containing vector data.  ALL of these layer worked with WWJ v2.1.0, but after the change in the MercatorTiledImageLayer in WWJ-CE we are having problems with the layers that contain vector data (streets, boundaries, etc.).  

When the layers that contain vector data load it looks like there are missing tiles in various locations as you zoom in and out.  We know the tiles aren't missing, so I'm guessing there's something about the way the tiles are being requested that's changed.

If I revert to WWJ v2.1.0 ALL of these same Mapbox layers display without any problems.  I'm new to Git/GitHub, but I'm wondering if there's a way for me to revert my local copy of WWJ-CE to a point before the change to the MercatorTiledImageLayer was merged in order to confirm if this is when the issue appeared?  I'll poke around and see if I can figure out how to do that.

If there's another/better way to display all our Mapbox maps in WWJ I'd love some pointers.  Otherwise I need to figure out what happened and get this corrected one way or another.

**Edit**
I figured out how to revert to just before the change to MercatorTiledImageLayer, but this did not fix the issue.  If I use WWJ v2.1.0 the problem goes away.  I guess I can keep reverting until I discover the point at which the problem goes away.  Any thoughts on what may have caused this and how to fix it are certainly welcome.

**Expected behavior:** 
All of our Mapbox maps should load as they did while using WWJ v2.1.0.

**Actual behavior:** 
Mapbox maps containing vector data (streets, boundaries, etc.) look like they are missing tiles at various locations as the map is zoomed in and out.

### Steps to Reproduce
I suppose this would be hard for anyone that doesn't use Mapbox maps.  However, simply set up a map from Mapbox that contains vector data (using the OSMMapnikLayer as an example).

**Reproduces how often:** 
100% of the time

### Operating System and Version 
Windows 10

**Comment by Sufaev** [comment]
Hello.
Could you provide a class which you are using to connect MapBox, so we can try to reproduce a bug.
Or at least url builder.

**Comment by robmilton** [comment]
I've temporarily made a very simple "black" map available with a temporary access token (included in the code below).  I just used the OSMMapnikLayer as a template.

If you scroll in particularly around the coast around the US you'll easily observe the issue.  A great place to zoom in is around San Francisco.

Here's the class:
```
public class BN_Mapbox_Black extends BasicMercatorTiledImageLayer {
    static String tempToken = "pk.eyJ1IjoiYWlycG9ydG1hc3RlciIsImEiOiJjand4azM3M2MwMXMzNGFxcjZwMXR5MjJqIn0.rtQ97ju2aDx_TZ_1rl-o7g";
    static String strName = "BN_Mapbox_Black";

    public BN_Mapbox_Black() {
        super(strName, "Earth/" + strName, 20, 256, false, ".png", new URLBuilder());
    }

    private static class URLBuilder extends MercatorTileUrlBuilder {

        @Override
        protected URL getMercatorURL(int x, int y, int z) throws MalformedURLException {
            String key = "?access_token=" + tempToken;
            return new URL("https://api.mapbox.com/styles/v1/airportmaster/cjhjerqz72m0e2smwjmlzm5sm/tiles/256/" + z + "/" + x + "/" + y + key);
        }
    }

    @Override
    public String toString() {
        return strName;
    }
}
```

**Comment by Sufaev** [comment]
Have you checked an application log during browsing that regions? What result message of image retriever do you see?

**Comment by robmilton** [comment]
@Sufaev is there a log that prints the image retriever messages that I can enable/find?  Or are you talking about me added print statements somewhere?

**Comment by Sufaev** [comment]
When you run application in Idea or Eclipse it shows error messages in console among other messahes when image was not retrieved.

Are you able to review this log when viewing the bug area? It will give an answer if retrieval failed or it even not request required tiles.

I plan to do it myself to analyse the issue, but i have no time bearest several days to do it immediatelly.

**Comment by gbburkhardt** [comment]
To see more retriever messages, run your application with JVM arg "-Djava.util.logging.config.file=logging.properties", and set ".level=FINEST" in 'logging.properties'.  

For Netbeans 8.2, using the Gradle run task, I needed to set "jvm-line-args=-Djava.util.logging.config.file=logging.properties" in Project Properties|Custom Variables.

You can limit the FINEST logging by adding  a line to 'logging.properties' that applies only to Worldwind:
 "gov.nasa.worldwind.level=FINEST".

**Comment by robmilton** [comment]
Thanks for the instructions.  So far I haven't been able to turn on logging.  I'm using NetBeans 11, and the project is an Ant project.  

I added VM option -Djava.util.logging.config.file=logging.properties through the Project Properties dialog.  I also tried -Djava.util.logging.config.file="logging.properties".

My project did not have a logging.properties file, so I created one under the nbproject folder.  I added .level=FINEST.  I also tried level=FINEST.

Any additional tips on how to get the logger working?  I'll keep experimenting with it.

**Comment by gbburkhardt** [comment]
There is a 'logging.properties' file that's part of the repository, and my references to making changes are to it.
I didn't find a place to set the JVM arguments in Netbeans 11.  My opinion at the moment is that Netbeans 11 isn't ready for prime time.

It did work for me using Netbeans 8.2, the Gradle project, and setting a custom variable:
![image](https://user-images.githubusercontent.com/5366676/59567640-1c60f880-903e-11e9-8f2c-cb94e44924a6.png)

So when running the WorldWindow sample application, one sees in the output pane:
Executing: gradle :run
Arguments: [-PmainClass=gov.nasa.worldwindx.applications.worldwindow.WorldWindow, -PcmdLineArgs=, -PjvmLineArgs=-Djava.util.logging.config.file=logging.properties, -c, C:\Users\glenn\Documents\repos\WorldWindJava\settings.gradle]

and then retriever messages:

Jun 16, 2019 1:55:38 PM sun.net.www.protocol.http.HttpURLConnection writeRequests
FINE: sun.net.www.MessageHeader@556c39be5 pairs: {GET /wms?EXCEPTIONS=application/vnd.ogc.se_xml&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0 HTTP/1.1: null}{User-Agent: Java/1.8.0_202}{Host: worldwind25.arc.nasa.gov}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
Jun 16, 2019 1:55:38 PM sun.net.www.protocol.http.HttpURLConnection writeRequests
FINE: sun.net.www.MessageHeader@284a07e65 pairs: {GET /elev?EXCEPTIONS=application/vnd.ogc.se_xml&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0 HTTP/1.1: null}{User-Agent: Java/1.8.0_202}{Host: worldwind26.arc.nasa.gov}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}

**Comment by robmilton** [comment]
Ok.  I was able to get logging working (my path to the logging.properties file was incorrect).

**Side Note**
Not sure if this should be taking place, but without any interaction whatsoever every 10 seconds the following messages get printed to the console:
```
Jun 16, 2019 3:46:02 PM sun.net.www.protocol.http.HttpURLConnection writeRequests
FINE: sun.net.www.MessageHeader@45b41a395 pairs: {GET / HTTP/1.1: null}{User-Agent: Java/1.8.0_201}{Host: worldwind.arc.nasa.gov}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
Jun 16, 2019 3:46:02 PM sun.net.www.protocol.http.HttpURLConnection getInputStream0
FINE: sun.net.www.MessageHeader@418b865714 pairs: {null: HTTP/1.1 200 OK}{Date: Sun, 16 Jun 2019 20:46:01 GMT}{Server: Apache}{Strict-Transport-Security: max-age=31536000;}{X-Frame-Options: sameorigin}{Last-Modified: Wed, 22 May 2019 19:30:22 GMT}{ETag: "280f-5897eff14ef80"}{Accept-Ranges: bytes}{Content-Length: 10255}{Vary: Accept-Encoding}{Access-Control-Allow-Origin: *}{Keep-Alive: timeout=5, max=100}{Connection: Keep-Alive}{Content-Type: text/html}
```

**Map Problem**
When I enable the layer that is having problems and begin to zoom in I get a bunch of messages like this:
```
Jun 16, 2019 3:48:15 PM sun.net.www.protocol.http.HttpURLConnection writeRequests
FINE: sun.net.www.MessageHeader@2e85ffe15 pairs: {GET /styles/v1/airportmaster/<mapId>/tiles/256/7/23/46?access_token=<token> HTTP/1.1: null}{User-Agent: Java/1.8.0_201}{Host: api.mapbox.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
Jun 16, 2019 3:48:15 PM sun.net.www.protocol.http.HttpURLConnection getInputStream0
FINE: sun.net.www.MessageHeader@445e706f16 pairs: {null: HTTP/1.1 200 OK}{Content-Type: image/png}{Content-Length: 1606}{Connection: keep-alive}{Date: Sun, 16 Jun 2019 14:41:58 GMT}{X-Powered-By: Express}{Access-Control-Allow-Origin: *}{Access-Control-Allow-Methods: GET}{Cache-Control: max-age=43200,s-maxage=43200}{X-Rate-Limit-Limit: 2000}{X-Rate-Limit-Interval: 60}{ETag: W/"646-odBij72xGoJMLxxVxDHxshKsUNk"}{Age: 21976}{X-Cache: Hit from cloudfront}{Via: 1.1 db929e55bb40b085896b8e336fba2ab7.cloudfront.net (CloudFront)}{X-Amz-Cf-Id: ynP3zjp2r5wusTTcppPXu2z8-ucQ17scB71daOabf4jfQ70XcSQsFg==}
Jun 16, 2019 3:48:15 PM gov.nasa.worldwind.retrieve.HTTPRetriever doRead
FINE: Response code 200, Content length 1,606, Content type image/png, retrieving https://api.mapbox.com/styles/v1/airportmaster/<mapId>/tiles/256/7/23/46?access_token=<token>
```
As I zoom in to an area where I'm getting blank or missing tiles i see the following messages in the log:
```
Jun 16, 2019 4:02:34 PM sun.net.www.protocol.http.HttpURLConnection writeRequests
FINE: sun.net.www.MessageHeader@559fc04c5 pairs: {GET /styles/v1/airportmaster/<mapId>/tiles/256/10/158/396?access_token=<token> HTTP/1.1: null}{User-Agent: Java/1.8.0_201}{Host: api.mapbox.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
Jun 16, 2019 4:02:34 PM sun.net.www.protocol.http.HttpURLConnection getInputStream0
FINE: sun.net.www.MessageHeader@672d4c0116 pairs: {null: HTTP/1.1 200 OK}{Content-Type: image/png}{Content-Length: 103}{Connection: keep-alive}{Date: Sun, 16 Jun 2019 21:02:33 GMT}{X-Powered-By: Express}{Access-Control-Allow-Origin: *}{Access-Control-Allow-Methods: GET}{Cache-Control: max-age=43200,s-maxage=43200}{X-Rate-Limit-Limit: 2000}{X-Rate-Limit-Interval: 60}{ETag: W/"67-1JzMAbxe/4kPVm67cU7inUOVtfg"}{X-Cache: Miss from cloudfront}{Via: 1.1 fc96a34d255c927c49d016d510d83ef9.cloudfront.net (CloudFront)}{X-Amz-Cf-Pop: IAH50-C2}{X-Amz-Cf-Id: fnTPJhNAkw-L4jNAD1ST-4iyE5x42FGLH2Cltt18BzXArQ9mCLav3g==}
Jun 16, 2019 4:02:34 PM sun.net.www.protocol.http.HttpURLConnection getInputStream0
FINE: sun.net.www.MessageHeader@5a52ee2a16 pairs: {null: HTTP/1.1 200 OK}{Content-Type: image/png}{Content-Length: 103}{Connection: keep-alive}{Date: Sun, 16 Jun 2019 21:02:33 GMT}{X-Powered-By: Express}{Access-Control-Allow-Origin: *}{Access-Control-Allow-Methods: GET}{Cache-Control: max-age=43200,s-maxage=43200}{X-Rate-Limit-Limit: 2000}{X-Rate-Limit-Interval: 60}{ETag: W/"67-1JzMAbxe/4kPVm67cU7inUOVtfg"}{X-Cache: Miss from cloudfront}{Via: 1.1 93818a791c595a1ca7a7d31c28fbcb86.cloudfront.net (CloudFront)}{X-Amz-Cf-Pop: IAH50-C2}{X-Amz-Cf-Id: 385x775IhIaCFPus0cmCUXqcfDZQQXDVGMvTuyPsZqaO9_5onXbS3A==}
Jun 16, 2019 4:02:34 PM gov.nasa.worldwind.retrieve.HTTPRetriever doRead
FINE: Response code 200, Content length 103, Content type image/png, retrieving https://api.mapbox.com/styles/v1/airportmaster/<mapId>/tiles/256/10/156/393?access_token=<token>
```
I did a little searching about the `{X-Cache: Miss from cloudfront}` which seems to relate to CloudFront caching.  But I don't know that this makes sense as a real issue since our other (raster) Mapbox maps load without issue.

Then after a short while I start getting messages like this:
```
Jun 16, 2019 4:10:00 PM gov.nasa.worldwind.retrieve.BasicRetrievalService$RetrievalExecutor beforeExecute
FINER: Cancelling request too long on the retrieval queue for https://api.mapbox.com/styles/v1/airportmaster/<mapId>/tiles/256/7/18/48?access_token=<token>
Jun 16, 2019 4:10:00 PM gov.nasa.worldwind.retrieve.BasicRetrievalService$RetrievalExecutor afterExecute
FINE: Retrieval of https://api.mapbox.com/styles/v1/airportmaster/<mapId>/tiles/256/7/21/47?access_token=<token> was cancelled
```
I'll continue to look through the log to see if I come across any other messages that add to the story.  I appreciate any thoughts/advice/help.

**Comment by Sufaev** [comment]
https://api.mapbox.com/styles/v1/airportmaster/<mapId>/tiles/256/7/18/48?access_token=<token>

Are you sure that you correctly pass token and map id in code?

It looks like you view map from local cache.

**Comment by robmilton** [comment]
Yes, I'm sure about the token and mapId.  I attempted to delete the mapId and token from each of the log entries I posted and replace them with `<mapId>` and `<token>` (since I was running the application  using our actual map and token...  not the temp map and token I included in the post above).  

Again, if I switch back to WWJ v2.1.0 all of these layers load and display correctly.  And the layers are identical (one of them is the " BN_Mapbox_BlackX extends BN_BasicMercatorTiledImageLayer" posted earlier in this thread).  The only change I had to make in our WWJ-CE-based project was to bring back a copy of "MercatorTextureTile" from v2.1.0 that returns MercatorTextureTile arrays from the "createSubTiles" function instead of TextureTile arrays.

> It looks like you view map from local cache.

I have intended to delete my map cache every time I run the application during this testing, but I may have forgotten to do so before one of these runs that I grabbed logger data from.  However, I have deleted the map cache many times.

I'm confident these layers that retrieve Mapbox maps haven't changed.  And if I use WWJ v2.1.0 they all load/display correctly.  So everything point to some change between WWJ v2.1.0 and WWJ-CE that is causing this behavior.

**Comment by robmilton** [comment]
So far I haven't seen anything else in the log that is helpful.  I don't understand why the other Mapbox layers still load/display without problem and why ALL the Mapbox layers load/display without problems if I go back to WWJ v2.1.0.

**Comment by wcmatthysen** [comment]
@robmilton, we can roll this change back and keep it on a separate branch until it is stable. @Sufaev, I don't know if that is ok for now?

**Comment by robmilton** [comment]
@wcmatthysen, I'm not 100% sure that the MercatorTiledImageLayer change is the issue.  I'm new to Git, but I believe I reset my clone of WWJ-CE to just before that change was merged.  But when I rebuilt WW and placed the new jar in my project I still had the same problems.  So possibly an earlier change in WWJ-CE is the actual cause?

I don't know if I should continue to reset my copy of WWJ-CE at various points further back to try to discover which merge coincides with the problem?

**Comment by robmilton** [comment]
Ok.  I reset my WWJ-CE project to commit "3399c8a - Update README.md" and the problem went away.  So unless you feel like there may be another commit/merger in there that could be responsible for this issue it seems that rolling back the change to MercatorTiledImageLayer may resolve this.

**Comment by Sufaev** [comment]
Am I correctly understand that reverting MercatorTiledImageLayer does not fix issue, and the problem is somewhere behinf 2.1.0 and MercatorTiledImageLayer enhancement?

**Comment by robmilton** [comment]
I'm not sure how to answer that.  I reverted to the commit just before the MercatorTiledImageLayer merge and the problem still existed.  So then I reverted to commit "3399c8a" and the problem went away.

So I'm not sure where I would need to revert to in order to eliminate the MercatorTiledImageLayer change as the problem.  What I do know is that reverting to commit "3399c8a" caused the problem to go away.

So does that mean that the change to MercatorTiledImageLayer is not the issue?  If you provide me with a commit to revert to that eliminates the possibility of the change to MercatorTiledImageLayer being the issue then I'll give that a try as well.

**Comment by robmilton** [comment]
@Sufaev, what commit would be the oldest/earliest that was related to the MercatorTiledImageLayer changes?  Is "9f17925" the oldest/first commit that is associated with this change?  If so should I just revert to "1855da5"?  Would this tell us if the issue lies in the MercatorTiledImageLayer changes?

Or is another method I can use to "roll back" the changes to the MercatorTiledImageLayer merge other than reverting the project to a specific commit?

**Comment by Sufaev** [comment]
I will try to debug tomorrow. By the way, could you record some short video or make a screenshot of a problem?

**Comment by robmilton** [comment]
I've reverted as far back as "86454FA" but still have the problem.  I'll keep working on this tomorrow, but I've got meetings I have to attend now.

I've attached a couple of screenshots of the problem.  The first 2 images show the problem with missing tiles on the globe.  The last 2 images show what the globe should look like.

If I continue to zoom in the positions of the missing tiles change but you continue to have many missing tiles at all zoom levels.

![bad1](https://user-images.githubusercontent.com/94461/59633828-007b5680-9113-11e9-88a0-7f408f87890b.jpg)
![bad2](https://user-images.githubusercontent.com/94461/59633834-02ddb080-9113-11e9-9816-49ae9ad9bf83.jpg)
![good1](https://user-images.githubusercontent.com/94461/59633837-05400a80-9113-11e9-8ab9-70e607fe79e6.jpg)
![good2](https://user-images.githubusercontent.com/94461/59633839-0709ce00-9113-11e9-868b-51dc70775db0.jpg)

**Comment by wcmatthysen** [comment]
@robmilton, I've tried to follow what you did and it seems to be the upgrade to JOGL 2.3.2. You mentioned that you checked out 3399c8a and you had no problems. That commit is just before the JOGL upgrade. The 86454fa commit is just after the JOGL upgrade where you seem to have the abovementioned problems. Can you just double-check that this is the case?

**Comment by robmilton** [comment]
@wcmatthysen, I think you're right.  Just to make sure I reverted to `010ef7f` and the problem went away.  So then I reverted to `3a1f84d` and the problem appeared.  It seems like the upgrade to JOGL 2.3.2 triggered the issue.  Is there anything that stands out as an obvious reason to you?

I've got more meetings I have to participate in, but as soon as I get a chance I'm going to dig through any JOGL related code changes that might have impacted the Mercator classes (and/or classes they extend).

**Comment by wcmatthysen** [comment]
@robmilton, I'm not sure how the JOGL upgrade causes this issue. We basically just switched to the latest JOGL jars and updated a couple of imports in the WorldWind code base as the latest version of JOGL changed package names. However, what I suggest is that you perhaps first try to upgrade your graphics card driver to the latest version and see if that fixes the issue. Otherwise we'll have to dig through the code to determine the cause.

**Comment by robmilton** [comment]
@wcmatthysen, I checked my drivers, and I don't think there's an issue with them.  My laptop has dual video cards.  The NVidia driver is the latest from NVidia.  The Intel driver is the latest from Dell (not the latest from Intel, but I'd rather stick with the driver Dell has released unless there's a specific reason to modify).  Below are the details...

```
  NVIDIA GeForce GTX 980M    Driver Date  5/22/2019    Driver Version  26.21.14.3086  OpenGL 4.6
  Intel HD Graphics 530      Driver Date  2/28/2018    Driver Version  23.20.16.4973  OpenGL 4.5
```
I am able to select which video card is used when launching an application.  I have used both video cards, and I get the same results with both (the same problem exists with both).

**Comment by wcmatthysen** [comment]
@robmilton, maybe just test on another machine if you can to make sure that it is not graphics card related.

**Comment by Sufaev** [comment]
Sorry, that I still did not join debugging of this problem (very busy last few days at work), but I have several ideas to check:
1) Have you tried to copy URL, produced by new URLBuilder which is based on new MercatorURLBuilder, when you begin to experience a bug, and paste it to browser to check if URL is correctly open an image? If not, than the problem is in URL preparation.
2) Have you checked if image retiever successfully download this image and parse this url? If not, it can be CORS problem with https etc.
3) Looking to your screenshots it seems that system skip tiles which are completely filled with one grey color and displays those which have some content, is it true or I mistake?

I do not think that new code can download and display one tiles and do not download another - the reason is somewhere in filtering conditions, for example tiles may be skipped if they reach maximum allowed level of details, based on distance to tile (i saw your old code has override level of details), or tiles can be skipped if skipBlanls flag is set and  then completely transparent tiles are skipped, or you set not enough number of levels.

I am trying to do my best to look at this problem myself also.

**Comment by robmilton** [comment]
@wcmatthysen, the issue is happening on many computers.  Each of my managers and several customers have reported the problem.  We have enough other maps available that I can hold off rolling back a little longer.  But this appears to be happening on every machine that runs the application.

**Comment by robmilton** [comment]
In addition to the tiling issue I've noticed that the color of the maps (for those that contain raster data) is quite different.  Below is a shot of the original map as it appears straight from Mapbox (and it looks this way if I revert to before the JOGL change) followed by a shot of the way the map looks now.

** Correct Colors **
![osmgood1](https://user-images.githubusercontent.com/94461/59794547-d48cdc00-929e-11e9-98b5-fb509bd84e9f.jpg)

** After JOGL Change **
![osmbad1](https://user-images.githubusercontent.com/94461/59794566-e0789e00-929e-11e9-88f0-0473f5ec563c.jpg)

**Comment by robmilton** [comment]
@Sufaev, thanks for the thoughts about troubleshooting.  

> Have you tried to copy URL, produced by new URLBuilder which is based on new MercatorURLBuilder, when you begin to experience a bug, and paste it to browser to check if URL is correctly open an image? If not, than the problem is in URL preparation.
- I've attempted to do this.  It's hard to determine which tiles are being displayed "correctly" and which aren't, and I'm not sure how to figure out the URL for a specific location on the map.  However, every URL I've grabbed from the log has returned a tile.

> Have you checked if image retiever successfully download this image and parse this url to BufferedImage and then reproject it by post downloading process without exeptions? If not, it can be CORS problem with https etc.
- I'm not sure how to perform the steps in number 2.  I'll have to dig into this.  However, it would seem strange to me that a CORS issue would affect just some of the tiles.

> Looking to your screenshots it seems that system skip tiles which are completely filled with one grey color and displays those which have some content, is it true or I mistake?
- I don't believe that's true 100% of the time.  I need to do some more testing, but I believe I have tiles not displaying correctly that should have some content drawn in them.  I'll have to get back to you on that.

**Comment by robmilton** [comment]
> Looking to your screenshots it seems that system skip tiles which are completely filled with one grey color and displays those which have some content, is it true or I mistake?
- It does look this way from the screen captures posted so far.  But at different zoom levels and different locations there are definitely tiles with content that don't display correctly (see below).

This is interesting.  The screen capture below shows the map at zoom level 10 (according to the "z" value being requested in the URL.  Notice the tile just north of the San Francisco airport is blank/black (I added the red square around the tile I'm talking about).
![mapmissing](https://user-images.githubusercontent.com/94461/59803759-15422080-92b2-11e9-96bc-c59ec539d55b.jpg)

By experimenting with the URL I was able to discover that the tile that should appear just north of the San Francisco airport is found [here](https://api.mapbox.com/styles/v1/airportmaster/cjhjerqz72m0e2smwjmlzm5sm/tiles/256/10/163/395?access_token=pk.eyJ1IjoiYWlycG9ydG1hc3RlciIsImEiOiJjand4azM3M2MwMXMzNGFxcjZwMXR5MjJqIn0.rtQ97ju2aDx_TZ_1rl-o7g
) and looks like this:
![missingtile](https://user-images.githubusercontent.com/94461/59803919-913c6880-92b2-11e9-996a-19858c942aa2.jpg)

After finding this tile to focus on I killed the application, cleared my map cache, then relaunched the app.  I see two references to this tile in the logs (see below), but the tile never displays.  Here are the two log entries that reference this tile:
```
Jun 19, 2019 5:07:09 PM sun.net.www.protocol.http.HttpURLConnection writeRequests
FINE: sun.net.www.MessageHeader@27b53f795 pairs: {GET /styles/v1/airportmaster/cjhjerqz72m0e2smwjmlzm5sm/tiles/256/10/163/395?access_token=pk.eyJ1IjoiYWlycG9ydG1hc3RlciIsImEiOiJjand4azM3M2MwMXMzNGFxcjZwMXR5MjJqIn0.rtQ97ju2aDx_TZ_1rl-o7g HTTP/1.1: null}{User-Agent: Java/1.8.0_201}{Host: api.mapbox.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
Jun 19, 2019 5:07:09 PM gov.nasa.worldwind.retrieve.HTTPRetriever doRead
FINE: Response code 200, Content length 2,176, Content type image/png, retrieving https://api.mapbox.com/styles/v1/airportmaster/cjhjerqz72m0e2smwjmlzm5sm/tiles/256/10/163/395?access_token=pk.eyJ1IjoiYWlycG9ydG1hc3RlciIsImEiOiJjand4azM3M2MwMXMzNGFxcjZwMXR5MjJqIn0.rtQ97ju2aDx_TZ_1rl-o7g
```

> Have you checked if image retiever successfully download this image and parse this url to BufferedImage and then reproject it by post downloading process without exeptions? If not, it can be CORS problem with https etc.
- It seems that the "Response code 200" in the log entry would rule out a CORS issue, don't you think?

It's beyond me at this point how a JOGL upgrade is tied to this.  I'll keep digging.

**Comment by wcmatthysen** [comment]
@robmilton, I'm seeing a similar issue. I created a `MapboxLayer` class for testing purposes and signed up for a mapbox account to test (using the free-tier). The class I'm using is:

    package gov.nasa.worldwind.layers.Earth;

    import gov.nasa.worldwind.avlist.AVKey;
    import gov.nasa.worldwind.avlist.AVList;
    import gov.nasa.worldwind.avlist.AVListImpl;
    import gov.nasa.worldwind.geom.Angle;
    import gov.nasa.worldwind.geom.LatLon;
    import gov.nasa.worldwind.layers.mercator.BasicMercatorTiledImageLayer;
    import gov.nasa.worldwind.layers.mercator.MercatorSector;
    import gov.nasa.worldwind.util.LevelSet;
    import gov.nasa.worldwind.util.Tile;
    import gov.nasa.worldwind.util.TileUrlBuilder;

    import java.net.MalformedURLException;
    import java.net.URL;

    public class MapboxLayer extends BasicMercatorTiledImageLayer
    {

        public MapboxLayer()
        {
            super(makeLevels());
        }

        private static LevelSet makeLevels()
        {
            AVList params = new AVListImpl();

            params.setValue(AVKey.TILE_WIDTH, 256);
            params.setValue(AVKey.TILE_HEIGHT, 256);
            params.setValue(AVKey.DATA_CACHE_NAME, "Earth/Mapbox");
            params.setValue(AVKey.SERVICE, "https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/256/");
            params.setValue(AVKey.DATASET_NAME, "mb");
            params.setValue(AVKey.FORMAT_SUFFIX, ".png");
            params.setValue(AVKey.NUM_LEVELS, 16);
            params.setValue(AVKey.NUM_EMPTY_LEVELS, 0);
            params.setValue(AVKey.LEVEL_ZERO_TILE_DELTA, new LatLon(Angle
                            .fromDegrees(22.5d), Angle.fromDegrees(45d)));
            params.setValue(AVKey.SECTOR, new MercatorSector(-1.0, 1.0,
                            Angle.NEG180, Angle.POS180));
            params.setValue(AVKey.TILE_URL_BUILDER, new URLBuilder());

            return new LevelSet(params);
        }

        private static class URLBuilder implements TileUrlBuilder
        {
            public URL getURL(Tile tile, String imageFormat) throws MalformedURLException
            {
                String urlPostfix = "?access_token=<access_token_here>";
                return new URL(tile.getLevel().getService()
                    + (tile.getLevelNumber() + 3) +"/"+ tile.getColumn()+"/"+ ((1 << (tile.getLevelNumber()) + 3) - 1 - tile.getRow()) + urlPostfix);
            }
        }

        @Override
        public String toString()
        {
            return "Mapbox";
        }
    }

In the code-snippet above I replaced the <access_token_here> with the one I got from map-box. I then added the `MapboxLayer` to `worldwind.layers.xml` and ran the `gov.nasa.worldwindx.examples.LayerTreeUsage` example. The results I got was similar to yours with missing tiles. However, I then manually reverted my version of JOGL back to how it was originally by getting the original jars and copying them to the WorldWind folder, changing the package names back to how they were (i.e. replacing `org.jogamp.opengl` with `javax.media.opengl` etc.) rebuilding WorldWind against the old JOGL. The funny thing is, that I'm still getting the issue. Here is the screenshot:

![Screenshot from 2019-06-20 10-59-10](https://user-images.githubusercontent.com/121888/59835981-ffcd0500-934a-11e9-814b-1d86b1ef8d0a.png)

I also made sure to clear my cache. So, I'm not exactly sure that this is a JOGL issue.

**Comment by wcmatthysen** [comment]
@robmilton, if you want you can check out my [branch](https://github.com/wcmatthysen/WorldWindJava/tree/mapbox-test). It contains the `MapboxLayer` class as well as the changes to revert to the previous version of JOGL. I just had to build the project with ant as the gradle build messed up in NetBeans.

**Comment by wcmatthysen** [comment]
@robmilton, I looked in my tile-cache directory and it seems that there are white tiles in there. For example, in the `Earth/Mapbox/0/3` folder I see:

![tiles](https://user-images.githubusercontent.com/121888/59861951-117dcf00-9382-11e9-8990-603110fd36ab.png)

So, it seems that these tiles are fetched and processed from mapbox and the resulting white tiles are stored on disk.

**Comment by robmilton** [comment]
@wcmatthysen, that's very interesting and confusing.  I checked out your branch and saw exactly what you're describing.

I thought maybe there would be a difference if I used the classes we're using to define the layer (older WW classes we extended in order to be able to set the "splitScale" value).  So I added those classes and created two layers:  Mapbox_Black and Mapbox_Streets_OSMStyle.  All of the classes I added are in the `gov.nasa.worldwind.layers.Earth` package.  For simplicity I included a temporary token in the layer classes themselves.

However, I got the same results with these layers and classes as you got with the new BasicMercatorTiledImageLayer class.  There must be something else that changes when I revert to just before the JOGL merge.  I'll keep digging.

I created a repository called [mapboxtest](https://github.com/robmilton/mapboxtest) you can check out if you're interested in seeing the other classes we're using.

**Comment by robmilton** [comment]
@wcmatthysen, I'm seeing the same thing...

In my Mapbox_Streets_OSMStyle cache I get white tiles that I don't believe should be white:
![white](https://user-images.githubusercontent.com/94461/59867147-08293e00-9353-11e9-968a-c87959961c08.jpg)

In Mapbox_Black I get black tiles that I don't believe should be black:
![black](https://user-images.githubusercontent.com/94461/59867164-170ff080-9353-11e9-82f6-05ecb0a833bf.jpg)

And in the Mapbox_Streets_OSMStyle map the colors are wrong (as I mentioned in a post above):
![color](https://user-images.githubusercontent.com/94461/59867201-2b53ed80-9353-11e9-86d4-f0d6391ac299.jpg)

**Comment by robmilton** [comment]
Ok, I finally figured out the issue.  When I would revert to earlier commits in the WWJ-CE project I also had to revert to earlier commits in our project.  There was a single line in one class that had been changed that I didn't find until literally comparing line-by-line.

As I mentioned above we had created a copy of the "MercatorTiledImageLayer" from WWJ v2.1.0 so that we could expose the "splitScale" variable.  What I didn't realize was that there was an additional change that hadn't been documented in our "BasicMercatorTiledImageLayer" class that extends the "MercatorTiledImageLayer" class.

Inside "BasicMercatorTiledImageLayer" is a function called "transform".  Inside the function the WWJ v2.1.0 code retrieved the BufferedImage type, and if the type was equal to 0 it set the type equal to "BufferedImage.TYPE_INT_RGB".

Someone must have figured out that when working with the Mapbox maps this value needed to be "BufferedImage.TYPE_INT_ARGB".  Setting the type to ARGB fixes the blank tiles and coloring issues seen above.  Below is the function with the changes described:

```
    private BufferedImage transform(BufferedImage image, MercatorSector sector) {
        
        // *********************************************************************
//        // Old
//        int type = image.getType();
//        if (type == 0) type = BufferedImage.TYPE_INT_RGB;
        
        // New
        int type = BufferedImage.TYPE_INT_ARGB;
        // *********************************************************************
        
        BufferedImage trans = new BufferedImage(image.getWidth(), image.getHeight(), type);
        double miny = sector.getMinLatPercent();
        double maxy = sector.getMaxLatPercent();
        for (int y = 0; y < image.getHeight(); y++) {
            double sy = 1.0 - y / (double) (image.getHeight() - 1);
            Angle lat = Angle.fromRadians(sy * sector.getDeltaLatRadians() + sector.getMinLatitude().radians);
            double dy = 1.0 - (MercatorSector.gudermannianInverse(lat) - miny) / (maxy - miny);
            dy = Math.max(0.0, Math.min(1.0, dy));
            int iy = (int) (dy * (image.getHeight() - 1));
            for (int x = 0; x < image.getWidth(); x++) {
                trans.setRGB(x, y, image.getRGB(x, iy));
            }
        }
        return trans;
    }
```

The current "BasicMercatorTiledImageLayer" class in WWJ-CE contains a class called "MercatorDownloadPostProcessor" which has a method called "transformPixels" which calls "transformPixels" in the "AbstractRetrievalPostProcessor" class then the rest of the code is almost identical to the old "transform" function.  

Would it be beneficial to make some modifications so that the new Mercator classes will work with Mapbox maps?  I'm not exactly sure what that would entail, but I'd be glad to work on it as I have opportunity to do so.

**Comment by Sufaev** [comment]
I have already fixed related issue and have added additional check:
```
if (type == BufferedImage.TYPE_CUSTOM) type = BufferedImage.TYPE_INT_RGB;
else if (type == BufferedImage.TYPE_BYTE_INDEXED) type = BufferedImage.TYPE_INT_ARGB;
```
In my implementation I have replaced 0 with BufferedImage.TYPE_CUSTOM constant.
I leave TYPE_INT_RGB for TYPE_CUSTOM just because it was the same logic in original code.

Are you sure that other maps will not fail if they will be loaded with 24 bit color space by default?

**Comment by robmilton** [comment]
I see that the code you mentioned is currently in the "transformPixels" function in the "MercatorDownloadPostProcessor" class in "BasicMercatorTiledImageLayer".  However, when we use that code to load the Mapbox maps this problem still exists (see @wcmatthysen 's `mapbox-test branch` he posted yesterday).

I'm guessing that the `else if (type == BufferedImage.TYPE_BYTE_INDEXED)` test is not catching the Mapbox image tiles for some reason.  

> Are you sure that other maps will not fail if they will be loaded with 24 bit color space by default?
- No, I'm not sure.  That's what I meant when I said I'm not exactly sure what it would entail to incorporate the "fix".  Maybe there is a case that can be caught in the "if" statement you referenced.  Or maybe we include a custom TiledImageLayer class that handles these Mapbox maps.

**Comment by Sufaev** [comment]
Does PR #54 fixed current issue?

**Comment by gbburkhardt** [comment]
I think it's unlikely that PR #54 will fix this issue, but I haven't tried, nor have I had time to look into the Mapbox issue.  The bug #54 fixes has to do with files read in by GDAL that have no alpha band.  The Mapbox issue doesn't sound anything like that.

**Comment by robmilton** [comment]
I have not tested #54, but I also don't think it will address this issue.  I am not using a newer version of GDAL at this point.  Instead I copied the function and class from the old GDALUtils that allows me to load the version of GDAL that was included with WWJ v2.1.0.

As I mentioned above I believe the Mapbox tiles are not meeting the condition in the `else if (type == BufferedImage.TYPE_BYTE_INDEXED)` statement in the "transformPixels" function for some reason and so the `BufferedImage.TYPE_INT_ARGB` is not being set.  However, I'm having a hard time using the debugger on the WW project when running the "LayerTreeUsage" example.  So I haven't been able to verify this yet.

**Comment by robmilton** [comment]
I think I discovered the issue.  I'm not sure exactly why, but some of the Mapbox tiles are not being caught in the statement `else if (type == BufferedImage.TYPE_BYTE_INDEXED)` in "transformPixels".  I discovered that some of the tiles report a "type" of `BufferedImage.TYPE_BYTE_BINARY`.  So I modified the statement to be `else if (type == BufferedImage.TYPE_BYTE_INDEXED || type == BufferedImage.TYPE_BYTE_BINARY)`, and the Mapbox maps seem to load properly.

There is a secondary issue with the Mapbox maps that I mentioned earlier.  We created a copy of the old "MercatorTiledImageLayer" so that we could expose the "splitScale" variable.  This gave us the ability to influence the "needToSplit" function to improve the appearance of the Mapbox tiles.

I've modified a branch and placed it [here](https://github.com/robmilton/mapboxtest) if you'd like to take a look.  If you run the example "LayerTreeUsage" you'll see layers called "Mapbox_Black", "Mapbox_Streets_OSMStyle", "Mapbox_Black_2" and "Mapbox_Streets_OSMStyle_2".  All of these layers should load and color tiles correctly now.  The layers with the suffix "_2" use the new "MercatorTiledImageLayer", while the other two layers use the class "Mapbox_BasicMercatorTiledImageLayer".  If you zoom in fairly close on the "Mapbox_Streets_OSMStyle_2" layer you'll notice that the tiles look a little blurred.  Then if you switch to "Mapbox_Streets_OSMStyle" (without the "_2" suffix) the appearance of the map is better because of the "splitScale" value being modified.

Could the new "MercatorTiledImageLayer" be modified to provide influence over the "needToSplit" functionality in a similar fashion?

**Comment by Sufaev** [comment]
On my opinion it will be usefull to make needToSplit controllable from the box.
@wcmatthysen what do you think?

By the way, type of BufferedImage in transformation logic should influence only the availability of transparent pixels on resulted image. Incorrect value cause opaque overlays. But I do not understand how it can influence reading the image.

**Comment by wcmatthysen** [comment]
@Sufaev, we can definitely add functionality to control the `needToSplit` function via a `splitScale` variable. I think it will be best to add this, together with the bugfix of @robmilton into a new pull request that we can then merge into develop.

**Comment by gbburkhardt** [comment]
@wcmatthysen, I don't see the change for BufferedImage.TYPE_BYTE_BINARY fixing the problem demonstrated in your test branch, whether JOGL 2.3.2 is used or the older version is used.  I was able to duplicate the problem using @robmilton's test branch, and there, removing the code for BufferedImage.TYPE_BYTE_BINARY breaks the image.

I was never able to see any wrong color display as described in @robmilton's earlier [comment](https://github.com/WorldWindEarth/WorldWindJava/issues/53#issuecomment-504105168).

The 'OpenTopoMap' layer that's commented out in 'worldwind.layers.xml' has tiles that come in as TYPE_BYTE_BINARY as well.  Adding @robmilton's change to the standard code gets rid of large white sections in the Atlantic.  The layers OSMMapnikLayer, OSMCycleMapLayer, WikimapiaLayer also use the BasicMercatorTiledImageLayer class, but the servers for OSMMapnikLayer, OSMCycleMapLayer are down or require an API key, and WikimapiaLayer doesn't appear to have any TYPE_BYTE_BINARY tiles.

The change can be made to set the BufferedImage type to TYPE_INT_RGB, and it fixes the problem.  That might use a bit less memory.

I don't know enough about this type of data to say what the correct solution is.

**Comment by robmilton** [comment]
@gbburkhardt, we are hard-coding `int type = BufferedImage.TYPE_INT_ARGB;` to address the problem on our end (that's working with a class that extends the OLD (WWJ v2.1.0) BasicMercatorTiledImageLayer class).  If we set the type to TYPE_INT_RGB it does not fix the problem with the Mapbox maps.  Having the type set to TYPE_INT_RGB seems to be the cause of the problem.  And setting the type to TYPE_INT_ARGB is what corrected the issue.

**Comment by gbburkhardt** [comment]
I thought that the problem was when a tile came in with TYPE_BYTE_BINARY (12), that the type of the new BufferedImage wasn't changed. 

In the 2.1.0 NASA code, this test was done:

`if (type == 0)`
`        type = BufferedImage.TYPE_INT_RGB;`

@Sufaev changed this in commit [9f179252](https://github.com/WorldWindEarth/WorldWindJava/commit/9f17925270d1f5c45899dc48da040fe5f68c3dcf) to

`                int type = image.getType();` 
`                if (type == BufferedImage.TYPE_CUSTOM) type = BufferedImage.TYPE_INT_RGB;` 
`                else if (type == BufferedImage.TYPE_BYTE_INDEXED) type = BufferedImage.TYPE_INT_ARGB;` 

So if the incoming type is TYPE_BYTE_BINARY (12), in both cases, the type will be unchanged.  Your change made the type of the new buffer to be TYPE_INT_ARGB, which includes an alpha band.  I determined by experiment that the code could also be fixed by 

`                if (type == BufferedImage.TYPE_CUSTOM) type = BufferedImage.TYPE_INT_RGB;` 
`                else if (type == BufferedImage.TYPE_BYTE_INDEXED) type = BufferedImage.TYPE_INT_ARGB;` 
`                else if (type == BufferedImage.TYPE_BYTE_BINARY) type = BufferedImage.TYPE_INT_RGB;` 

using your test branch.

**Comment by wcmatthysen** [comment]
@gbburkhardt, the changes in my mapbox-test [branch](https://github.com/wcmatthysen/WorldWindJava/tree/mapbox-test) only demonstrated that the problem was still present when reverting back to the old JOGL. We tried to determine whether reverting to the old version of JOGL would fix the problem, and my branch demonstrated that it didn't have anything to do with the JOGL version.

It looks like you guys narrowed the problem down. I think we need to create a pull-request with this code to fix the bug (as mentioned by @gbburkhardt):

    if (type == BufferedImage.TYPE_CUSTOM) type = BufferedImage.TYPE_INT_RGB;
    else if (type == BufferedImage.TYPE_BYTE_INDEXED) type = BufferedImage.TYPE_INT_ARGB;
    else if (type == BufferedImage.TYPE_BYTE_BINARY) type = BufferedImage.TYPE_INT_RGB;

@robmilton, would you be able to create a pull-request for this? @gbburkhardt or I could help with this. We should add the ability to control the `splitScale` variable as mentioned earlier to avoid blurry maps.

**Comment by robmilton** [comment]
@wcmatthysen, I'd be glad to.  I'm not sure how to address the "splitScale" variable and "needToSplit" function, though, since the "splitScale" variable only existed in the WWJ v2.1.0 version of MercatorTiledImageLayer...  and the "needToSplit" function in that class is very different than the "needToSplit" function in the TiledImageLayer class.

I've experimented with using the "detailHint" variable to accomplish the same thing, but that hasn't worked.  I've also experimented with adding a "splitScale" variable and subtracting the value from the "scaledEyeDistanceMeters" value on line 520 of TiledImageLayer, but that hasn't worked either.

Any idea how to add a variable that gives the same ability to impact the "needToSplit" function as the "splitScale" variable provided in the WWJ v2.1.0 version of MercatorTiledImageLayer?

**Comment by wcmatthysen** [comment]
I'm not too familiar with those classes. I'll have to take a look at it. @Sufaev, would you be able to help with this?

**Comment by Sufaev** [comment]
@robmiltom Why detailHint and detailHintOrigin does not fit your requirements? I have used it to change level of details in my OpenStreetMap, Wikimapia and Google examples. What exactly do not work in your case?

**Comment by robmilton** [comment]
@Sufaev, please take a look at the [branch](https://github.com/robmilton/mapboxtest) I posted.  If you zoom in fairly close and compare the "Mapbox_Streets_OSMStyle" map to the "Mapbox_Streets_OSMStyle_2" map you'll see the difference I'm describing.  "Mapbox_Streets_OSMStyle_2" looks blurred compared to "Mapbox_Streets_OSMStyle".  

Maybe I just don't know how to use "detailHint" and "detailHintOrigin".  But the experimenting I've done has not produced similar results to the results we get when using the old MercatorTiledImageLayer's "needToSplit" function with the "splitScale" variable.

I am completely open to using "detailHint" and "detailHintOrigin" if they can be used to produce the same or very similar results seen in the "Mapbox_Streets_OSMStyle" map in my branch.

**Comment by Sufaev** [comment]
Current needToSplit method in BasicMercatorTiledImageLayer is based on comparing tile image pixel density in meters (texelSize) to current pixel density in tile sector center position, calculated based on camera distance to it. This approach determines when (on which camera distance) tile should be subdivided comparing current and desired pixel density. Method getDetailFactor consists of detailHint and detailHintOrigin determines multiplication factor. If getDetailFactor = 1, then tiles will split to next level of details when it reach 1:1 pixel density to current monitor pixel density. Default detailHintOrigin value = 2.8 means that map is subdivided only when the tile on the screen becomes 256*2.8 = 716 pxels. That's why you see blurred 3x scaled tiles.

Try to set detailHintOrigin = 1 or 1.5 for you map and see the result. If you will use 1, than text will be unreadable, because maps usually rendered to be scaled when used, because of high monitor density nowadays.
```
    protected boolean needToSplit(DrawContext dc, Sector sector, Level level)
    {
        double texelSize = level.getTexelSize() * dc.getGlobe().getRadius();
        double pixelSize = dc.getView().computePixelSizeAtDistance(sector.distanceTo(dc, dc.getView().getEyePoint()));
        return texelSize > pixelSize * this.getDetailFactor();
    }
```

Here are examples of the OpenTopoMap on 20km scale using default 2.8 scale and 1.0
![Знімок екрану з 2019-07-08 18-25-13](https://user-images.githubusercontent.com/12487306/60823433-2e9f0400-a1b0-11e9-94f8-569b19a32931.png)
![Знімок екрану з 2019-07-08 18-22-36](https://user-images.githubusercontent.com/12487306/60823432-2e066d80-a1b0-11e9-98fa-a88f8d63b8b7.png)

**Comment by robmilton** [comment]
@Sufaev, thanks for the explanation and directions.  It appears that using "setDetailHint" to set a "detailHint" value between -1.8 and -2.0 produces results very similar (if not identical) to the results we were getting by adjusting the "splitScale" value (to a value of 1.3) using the old "needToSplit" funcationality.

So it looks like the only change needed is the addition to the if statement to handle `BufferedImage.TYPE_BYTE_BINARY`.

**Comment by robmilton** [comment]
@wcmatthysen, I've created a branch with the change to handle the `BufferedImage.TYPE_BYTE_BINARY` (actually changed the existing "if" statement to a switch).  

**OLD**
```
                int type = image.getType();
                if (type == BufferedImage.TYPE_CUSTOM) {
                    type = BufferedImage.TYPE_INT_RGB;
                }
                else if (type == BufferedImage.TYPE_BYTE_INDEXED) {
                    type = BufferedImage.TYPE_INT_ARGB;
                }
```
**NEW**
```
                int type = image.getType();
                switch (type) {
                    case BufferedImage.TYPE_CUSTOM:
                        type = BufferedImage.TYPE_INT_RGB;
                        break;
                    case BufferedImage.TYPE_BYTE_INDEXED:
                        type = BufferedImage.TYPE_INT_ARGB;
                        break;
                    case BufferedImage.TYPE_BYTE_BINARY:
                        type = BufferedImage.TYPE_INT_RGB;
                        break;
                    default:
                        type = BufferedImage.TYPE_INT_RGB;
                        break;
                }
```



It appears this is all that is needed since @Sufaev described how to use "setDetailHint" to address the tiling issue I was having.

In order to test on my end I also added a Mapbox layer class to load one of our Mapbox maps and added an entry to the "worldwind.layers.xml" file.  The map class is using a temporary Mapbox token that will not be valid much longer.  Do you want me to push the branch and create a pull request with the map class and config file changes included?  Or just push the change to the "if" statement in the "BasicMercatorTiledImageLayer" class?

**Comment by Sufaev** [comment]
By the way, I do not remember why I have used this code of needToSplit when refactored this class. Probably it was taken from Android codebase.

I have looked that parent TiledImageLayer has similar code. Probably we can remove my overriden method. The difference is only in some additional "field of view scale" in parent method.

@robmilton could you try your test project with commented method needToSplit in Mercator class? Just to see what will happen.

**Comment by robmilton** [comment]
@Sufaev, the default of `BufferedImage.TYPE_INT_RGB` just seemed the most logical to me.  Do you have a suggestion?

I will comment out the "needToSplit" function in "BasicMercatorTiledImageLayer" and see what happens.  I have to jump onto another task at the moment.  But I'll hopefully get back to this later today or tomorrow.

**Comment by Sufaev** [comment]
@robmilton I do not completely understand how this BufferedImage type should be used in all other possible cases, that's why I have added a special ARGB case only for some transparent map layers which have appeared to be TYPE_BYTE_INDEXED and leave all other cases unchanged. May be some other types except indexed and binary should not be changed to RGB by default, but I do not know. I think we need assistance of someone who inderstand it better to make a final solutuon :)

As for needToSplit, I found interesting comment in TiledImageLayer:
NOTE: It's tempting to instead compare a screen pixel size to the texel size, but that calculation is window-size dependent and results in selecting an excessive number of tiles when the window is large.

I am not shure if they mean my solutuon or they spoke about viewport dimension to tile texel size comparation, but any way, if we comment overriden needToSplit method in mercator class we should have the same result, because FOV is equals 45 by default and its multiplication factor will equals 1 in that parent methot. So the result should be exactly the same. I do not understand why someone take FOV factor into account, but probably it was a reason for that. So, I propose to remove and commit needToSplit method in Mercator class if your tests will show successfull results.

**Comment by Sufaev** [comment]
I was not right.

The difference between methods is in the following code. They use detail factor not directly as multiplication factor (as I have used), but as pow of 10. Anyway we probably can use parent implementation with some suitable detail factor just to have the same behavior for all types of image layers (mercator and non-mercator).

double s = this.getDetailFactor();
        if (sector.getMinLatitude().degrees >= 75 || sector.getMaxLatitude().degrees <= -75)
            s *= 0.9;
        double detailScale = Math.pow(10, -s);

**Comment by robmilton** [comment]
I am still working on the other task I have to take care of.  However, I wanted to suggest that if no one has a better idea then maybe we do the following...

Leave the default behavior in the switch to use `BufferedImage.TYPE_INT_RGB` but add a log message that states:
`"An unexpected image type of '<type detected>' was encountered in MercatorDownloadPostProcessor.  Setting type to 'BufferedImage.TYPE_INT_RGB'." `

(replacing \<type detected\> with the image type encountered in the code.  

Just a thought...

**Comment by robmilton** [comment]
@Sufaev, after reading through this again I realized that the default case is not what I really intended at all.  I intended for the "type" variable to hold the value returned from image.getType() unless that result was equal to one of the 3 types we need to override.  So the switch statement should be:

```
                int type = image.getType();
                switch (type) {
                    case BufferedImage.TYPE_CUSTOM:
                        type = BufferedImage.TYPE_INT_RGB;
                        break;
                    case BufferedImage.TYPE_BYTE_INDEXED:
                        type = BufferedImage.TYPE_INT_ARGB;
                        break;
                    case BufferedImage.TYPE_BYTE_BINARY:
                        type = BufferedImage.TYPE_INT_RGB;
                        break;
                    default:
                        // leave value returned from image.getType()
                        break;
                }
```

The only negative about this approach is that the use of the wrong "type" in the code following this switch does not throw any errors or log any warnings.  I don't know that there's anything we can do to make this better.  But the absence of any errors or warnings contributed to the difficulty in tracking down the reason for the problem with the blank/empty tiles when the image type was `TYPE_BYTE_INDEXED`.  It would be nice if there was something we could key on to know that the image type is introducing problems...  but, again, I don't know of a good way to accomplish this.

**Comment by robmilton** [comment]
I commented out the "needToSplit" function in BasicMercatorTiledImageLayer, and it looks like the method in TiledImageLayer produces extremely similar results.

I can't tell if the maps in general look identical or not.  I've gone back and forth between the functions and I've run instances side-by-side.  I think the results look the same on the maps available in the LayerTreeUsage class.

However, using the function in the TiledImageLayer class behaves very differently in regards to the detailHint settings.  So far I haven't figured out a value for detailHint that gives results anywhere near setting the detailHint to -1.8 with the function in BasicMercatorTiledImageLayer.

1.  The Mapbox layer loads the initial set of tiles to cover the globe (when zoomed out).  But as you zoom in higher detail tiles are not retrieved (and it doesn't appear that they are even being requested).  However, it appears that allowing the default detailHint corrects this issue.  So it seems the detailHint would need to be set significantly differently with this code in order to address the appearance of the Mapbox maps.
2.  The other maps don't appear as clear/crisp to me.  However, this is hard to really determine since I'm not sure of a good way to run sessions side-by-side and not have one use the cache from the other.

**Comment by Sufaev** [comment]
I will try to figure out how correctly use detailHint when will be in office today.

Theoretically the difference is in the following:
1) Current Mercator approach use formula texelSize > pixelSixe * detailHint
2) Parent class approach use formula texelSize > pixelSize * Math.pow(10, -detailHint).

I can not say why it is used in such complex way, but it can defenetely be used with some other values to reach required split factor.

**Comment by robmilton** [comment]
The TiledImageLayer class has the following comments in the needToSplit function:
```
    // Compute the level of detail scale and the field of view scale. These scales are 
    // multiplied by the eye distance to derive a scaled distance that is then compared 
    // to the texel size. The level of detail scale is specified as a power of 10. For example, 
    // a detail factor of 3 means split when the cell size becomes more than one thousandth 
    // of the eye distance.  
    //
    // Split when the texel size in meters becomes greater than the specified fraction  of 
    // the eye distance, also in meters. Another way to say it is, use the current tile if its 
    // texel size is less than the specified fraction of the eye distance.
    //
    // NOTE: It's tempting to instead compare a screen pixel size to the texel size, but 
    // that calculation is window-size dependent and results in selecting an excessive 
    // number of tiles when the window is large.
```

> a scaled distance that is then compared to the texel size

So the comparison in the parent class is between the texel size and a scaled view distance.

The entire function is:
```
    protected boolean needToSplit(DrawContext dc, Sector sector, Level level) {
        double texelSizeRadians = level.getTexelSize();
        double texelSizeMeters = dc.getGlobe().getRadius() * texelSizeRadians;

        double s = this.getDetailFactor();
        if (sector.getMinLatitude().degrees >= 75 || sector.getMaxLatitude().degrees <= -75)
            s *= 0.9;
        double detailScale = Math.pow(10, -s);
        double fieldOfViewScale = dc.getView().getFieldOfView().tanHalfAngle() / Angle.fromDegrees(45).tanHalfAngle();
        fieldOfViewScale = WWMath.clamp(fieldOfViewScale, 0, 1);

        double eyeDistanceMeters = sector.distanceTo(dc, dc.getView().getEyePoint());
        double scaledEyeDistanceMeters = eyeDistanceMeters * detailScale * fieldOfViewScale;

        return texelSizeMeters > scaledEyeDistanceMeters;
    }
```

`this.getDetailFactor()` returns `detailHintOrigin + detailHint`.  And detailHintOrigin is defaulted to 2.8.

detailScale is calculated as `Math.pow(10, - <this.getDetailFactor>)`.  Then the detailScale is multiplied by the fieldOfViewScale and the eyeDistanceMeters to come up with the scaledEyeDistanceMeters.

There doesn't seem to be any provision for modifying the default value of 2.8 for detailHintOrigin.  And detailHint is added to detailHintOrigin in getDetailFactor().  

The setDetailHint() method has the following comments:
```
    Modifies the default relationship of image resolution to screen resolution as the viewing 
    altitude changes.  Values greater than 0 cause imagery to appear at higher resolution at 
    greater altitudes than normal, but at an increased performance cost. Values less than 0 
    decrease the default resolution at any given altitude. The default value is 0. Values 
    typically range between -0.5 and 0.5.
    
    Note: The resolution-to-height relationship is defined by a scale factor that specifies 
    the approximate size of discernible lengths in the image relative to eye distance. 
    The scale is specified as a power of 10. A value of 3, for example, specifies that 1 meter 
    on the surface should be distinguishable from an altitude of 10^3 meters (1000 meters). 
    The default scale is 1/10^2.8, (1 over 10 raised to the power 2.8). The detail hint 
    specifies deviations from that default. A detail hint of 0.2 specifies a scale of 1/1000, 
    i.e., 1/10^(2.8 + .2) = 1/10^3.  Scales much larger than 3 typically cause the applied 
    resolution to be higher than discernible for the altitude.  Such scales significantly 
    decrease performance.

    @param detailHint the degree to modify the default relationship of image resolution to
                      screen resolution with changing view altitudes.  Values greater than 1 
                      increase the resolution. Values less than zero decrease the resolution. 
                      The default value is 0.
```
I don't understand the statements in the detailHint param definition that state "Values greater than 1 increase the resolution. Values less than zero decrease the resolution."  These statements seem to be in conflict with the statement in the first paragraph that says "Values typically range between -0.5 and 0.5".

**After reading through all of this I began experimenting with setting the detailHint value within the range of -0.5 and 0.5.  And I found that a value of 0.3 produces the results I'm looking for.**

@Sufaev, can you confirm that you get desired results for your Mercator maps when setting the detailHint value between -0.5 and 0.5?

**Comment by Sufaev** [comment]
It looks like I really took needToSplit approach from Android code base:
```
    public boolean mustSubdivide(RenderContext rc, double detailFactor) {
        this.distanceToCamera = this.distanceToCamera(rc);
        double texelSize = this.texelSizeFactor * rc.globe.getEquatorialRadius();
        double pixelSize = rc.pixelSizeAtDistance(this.distanceToCamera);
        return texelSize > (pixelSize * detailFactor);
    }
```
Probably I have broke up the original meaning of detailHint, designed in Java TiledImageLayer and start using it as detailFactor from Android, but it is really not the same.

Current MercatorTiledImageLayer implementation in Java and Android use detailFactor (detailHint) as multiplication factor of pixel density at current camera distance to compare with texel density. So if factor equals 2 it means that subdivision will take place when tile size will be twice bigger than its size in pixels on the screen.

Java approach from TiledImageLayer according to comments use detailHint as the level of detail scale, specified as a power of 10 and applied not to pixelSize at specified camera distance, but to the camera distance itself. For example, a detail factor of 3 means split when the cell size becomes more than one thousandth of the eye distance. I do not understand why somebody decided to use such approach and what is the physical meaning of it, but it also can be used.

@robmilton When I use detailHint +0.5 it gives me similar result as -0.5 using Android code. Here is a 20km scale with detailHint = +0.5.
![Знімок екрану з 2019-07-09 17-25-48](https://user-images.githubusercontent.com/12487306/60896282-c06d4680-a26e-11e9-8dc9-7d64ba1005b6.png)

**Comment by robmilton** [comment]
@Sufaev, your map looks pretty good to me.  Are you getting results that you are happy with when adjusting using detailHint?  If so do you agree that we should remove needToSplit from BasicMercatorTiledImageLayer and let the function in TiledImageLayer take care of things?

**Comment by Sufaev** [comment]
@robmilton From one side I agree to have similar detail control approach in any types of image layers, but from other side... BINGO!!!

I just found the reason why I had override needToSplit method during refactoring and why default 2.8 detailHintOrigin looks so blur! It does not take map window with into account and was probably designed for 1280x1024 window size :)

Try to resize map window width and you will see that map details does not change when map becomes very narrow or very wide! It remains with same details. That's why on FullHD monitor details looks ugly blur.
![Знімок екрану з 2019-07-09 17-50-42](https://user-images.githubusercontent.com/12487306/60898852-2a3b1f80-a272-11e9-90c2-25fa44ae323b.png)

My approach, copied from Android code change dettails when you resize window. So, I have counterclaim - remove needToSplit from MercatorLayer but replace TiledImageLayer needToSplit with new approach, which works correctly during window resize for any image layers. And probably it should be done as separate PR.

**Comment by robmilton** [comment]
@Sufaev, I'm not seeing the same behavior.  I'm using the LayerTreeUsage class in worldwindx.examples.  When I change the width of the screen the map details do change.  As the screen gets wider the map details grow in size.  And as the screen gets narrower the map details shrink in size.  Below are some examples...

**Mid-Size Window**
![test_mid](https://user-images.githubusercontent.com/94461/60900202-6e5a0000-a231-11e9-89a1-c873d0974abf.jpg)

**Wide Window**
![test_wide](https://user-images.githubusercontent.com/94461/60900235-79ad2b80-a231-11e9-80cf-38a314d33c3b.jpg)

**Narrow Window**
![test_narrow](https://user-images.githubusercontent.com/94461/60900260-83369380-a231-11e9-9734-81738c210ae9.jpg)

**Comment by Sufaev** [comment]
@robmilton Probably you do not understand what I mean. Your screenshots clearly display this bug. Look at the Road name signs. They should remain the same size, but on your bottom screenshot they become small. This means that map details does not switch.

**Comment by robmilton** [comment]
@Sufaev, I guess I did not understand you initially.  However, I'm not sure if I would consider this a bug.  This seems like expected behavior to me.  I would think you would want everything to scale/adjust based on screen size.

When would you want the details to remain the same size regardless of screen size?

**Comment by Sufaev** [comment]
The details will remain the same when you change screen height, but when you change width you actually zoom out the map, because system apply the same field of view to another screen witdh. If map will not change details, you will see unreadable small or blurry big texts and other map elements.

Furthermore, if you release your software with some detailHintOrigin it will have different details not depending on pixel density but depening on screen width. Screens with big resolution will have blur map.

I assume that details should change when map tile in 3d space become twice bigger or twice smaller. So when you resize window two times - it switch level of details and make map text and other details fit your current zoom.

**Comment by Sufaev** [comment]
By the way both Android and Web versions use approach which I described. The only difference - Web use vertical field of view in its camera calculations and change zoom when you change height.

**Comment by wcmatthysen** [comment]
@robmilton, @Sufaev if you guys have changes / fixes you can create a new branch and push commits to it. You can then create a pull-request from this branch and add commits to it. @robmilton you can add a MapBoxLayer to the commits on this branch as well. I don't think it is necessary to create a separate pull request for the MapBoxLayer class. I created a MapBoxLayer class earlier in this discussion that you can have a look at. This class allows you to set the access-token via XML as follows:

    <Layer className="gov.nasa.worldwind.layers.Earth.MapboxLayer" actuate="onRequest">
        <Property name="AccessToken" value="<access-token-here>"/>
    </Layer>

Thus, you don't need to have a temporary access-token.

**Comment by robmilton** [comment]
@wcmatthysen, I created a branch and attempted to push it but I get the following git error:
`https://94461%2brobmilton%40users.noreply.github.com@github.com/WorldWindEarth/WorldWindJava.git: git-receive-pack not permitted`

Do I need permissions of some sort to push to the project?

**Comment by wcmatthysen** [comment]
@robmilton, it might be your credentials. See: https://stackoverflow.com/questions/10475726/git-receive-pack-not-permitted-on-push

**Comment by wcmatthysen** [comment]
@robmilton, also make sure you push to your own fork and not this repository. You can still create the pull-request on this repository. But the branch that you create should be on your own fork and you should push the changes to your own fork.

**Comment by Sufaev** [comment]
I have created new issue about level of details selection https://github.com/WorldWindEarth/WorldWindJava/issues/60

Lets fix ImageBuffer type and close this issue.

What have we decide about default type? Will we override any other type with RGB or leave them unchanged and will solve problems with them when they appears?

**Comment by robmilton** [comment]
@wcmatthysen, Ok I was able to create a pull request.  Yesterday I was trying to push to this repository.  Once I created my own fork I was able to push the branch (sorry, still very much a Git newbie here!).

@Sufaev, I think we should only override the 3 types that have been identified and leave any others unchanged.  As mentioned earlier it's just a shame that there isn't a way to indicate this may be the source of tiling display issues.

**Comment by robmilton** [comment]
Is there anything else you need me to do at this point?

**Comment by wcmatthysen** [comment]
We can close this issue for now. The level-of-detail discussion can continue in issue #60.
